name: aicycle_buyme_lib
description: A new Flutter package project.
version: 0.0.1
homepage: https://aicycle.ai/

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  camera: ^0.10.5+5
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  get: ^4.6.6
  image: ^4.1.3
  logger: ^2.0.2+1
  mime: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  photo_view: ^0.14.0
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/gif/